<a href="https://colab.research.google.com/github/mekaviraj/ML_sem5/blob/main/ml_lab_sem5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[ML drive folder](https://drive.google.com/drive/folders/123m4M0v0Kp9VL58w-AEbm_m9sNgQ10TD)

# week 1


In [ ]:
import pandas as np

In [ ]:
df = np.DataFrame([])

In [ ]:
# chatgpt is making our brain dumb


In [ ]:
obj + 2

NameError: name 'obj' is not defined

In [ ]:
obj + obj

NameError: name 'obj' is not defined

In [ ]:
2+ obj


NameError: name 'obj' is not defined

In [ ]:
lst = [1,2]
lst.append(lst)
l = 0
print(lst[2])
print(lst)

[1, 2, [...]]
[1, 2, [...]]


In [ ]:
import numpy as np


n =np.array([1,2,333,4,5]).reshape(5,1)

n[n % 2 != 0 ] = -1
print(n)

[[-1]
 [ 2]
 [-1]
 [ 4]
 [-1]]


In [ ]:
"""How do you create a 3x3 matrix filled with zeros?

How do you create a 1D NumPy array with numbers from 0 to 9?

How do you access the last element of a 2D array?

How do you select all elements in the second column of a 3x3 array?

How can you reshape a 1D array of size 9 into a 3x3 matrix?

How do you multiply two NumPy arrays element-wise?

How do you calculate the dot product of two NumPy arrays?

How do you calculate the mean, median, and standard deviation of a NumPy array?

How do you filter out values less than 5 from a NumPy array of random integers between 1 and 10?

How can you transpose a 3x2 array to a 2x3 array?

How do you find the index of the maximum value in a NumPy array?

How do you replace all negative values in a NumPy array with 0?

How do you stack two NumPy arrays vertically and horizontally?

How do you concatenate two 1D arrays into a single 1D array?

How do you get the sum of each column in a 2D NumPy array?

"""

'How do you create a 3x3 matrix filled with zeros?\n\nHow do you create a 1D NumPy array with numbers from 0 to 9?\n\nHow do you access the last element of a 2D array?\n\nHow do you select all elements in the second column of a 3x3 array?\n\nHow can you reshape a 1D array of size 9 into a 3x3 matrix?\n\nHow do you multiply two NumPy arrays element-wise?\n\nHow do you calculate the dot product of two NumPy arrays?\n\nHow do you calculate the mean, median, and standard deviation of a NumPy array?\n\nHow do you filter out values less than 5 from a NumPy array of random integers between 1 and 10?\n\nHow can you transpose a 3x2 array to a 2x3 array?\n\nHow do you find the index of the maximum value in a NumPy array?\n\nHow do you replace all negative values in a NumPy array with 0?\n\nHow do you stack two NumPy arrays vertically and horizontally?\n\nHow do you concatenate two 1D arrays into a single 1D array?\n\nHow do you get the sum of each column in a 2D NumPy array?\n\n'

In [ ]:
"there are 4 pdfs , by 11 complete minimum 4- sai ram"

'there are 4 pdfs , by 11 complete minimum 4- sai ram'

In [ ]:
import numpy as np
n = np.zeros((3,3))
print(n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import pandas as pd


In [ ]:
print(np.arange(3,3))

[]


In [ ]:
print(n[-1])

[0. 0. 0.]


In [ ]:
n = np.arange(9).reshape(3,3)
print(n)
print(n[1][::])# 2nd coulum all ele ela?


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]


In [ ]:
m = n
mm = n.dot(m)

In [ ]:
print(mm)

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


# Week 2



In [ ]:
import sklearn


In [ ]:
from sklearn import datasets

In [ ]:
df = datasets.load_iris()

In [ ]:
# Import necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Labels

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a logistic regression model
model = LogisticRegression(max_iter=200)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 100.00%


In [ ]:

print(f"Accuracy: {accuracy }%")

Accuracy: 1.0%


In [ ]:
iris_path = "/content/Iris.csv"

In [ ]:
# Write a Python program to load the iris data from a given csv file into a dataframe and
# print the shape of the data, type of the data and first 3 rows.

import pandas as pd
iris_path = "/content/Iris.csv"
# df = pd.DataFrame(iris_path)
df = pd.read_csv(iris_path)
# example = pd.DataFrame()
print("---------------type---------------------------------")
# print(type(example))
print(type(df))
print("----------------------shape--------------------------")
print(df.shape)
print("---------------------------info---------------------")
print(df.info)
print("-------------------------------head-----------------")
print(df.head(3))

---------------type---------------------------------
<class 'pandas.core.frame.DataFrame'>
----------------------shape--------------------------
(150, 6)
---------------------------info---------------------
<bound method DataFrame.info of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4         

In [ ]:
# Write a Python program using Scikit-learn to print the keys, number of rows-columns,
# feature names and the description of the Iris data.

import sklearn



In [ ]:
# feature names and the description of the Iris data.
# 3. Write a Python program to get the number of observations, missing values and nan
# values.
# 4. Write a Python program to view basic statistical details like percentile, mean, std etc.
# of iris data.
# 5. Write a Python program to get observations of each species (setosa, versicolor,
# virginica) from iris data.
# 6. Write a Python program to drop Id column from a given Dataframe and print the
# modified part. Call iris.csv to create the Dataframe.
# 7. Write a Python program to access first four cells from a given Dataframe using the
# index and column labels. Call iris.csv to create the Dataframe.
# 8. Write a Python program to create a plot to get a general Statistics of Iris data.
# 9. Write a Python program to create a Bar plot to get the frequency of the three species
# of the Iris data.
# 10. Write a Python program to create a Pie plot to get the frequency of the three species of
# the Iris data.
# 11. Write a Python program to create a graph to find relationship between the sepal length
# and width.
# 12. Write a Python program to create a graph to find relationship between the petal length
# and width.
# 13. Write a Python program to create a graph to see how the length and width of
# SepalLength, SepalWidth, PetalLength, PetalWidth are distributed.
# 14. Write a Python program to create a joinplot to describe individual distributions on the
# same plot between Sepal length and Sepal width.
# 15. Write a Python program to create a joinplot using "hexbin" to describe individual
# distributions on the same plot between Sepal length and Sepal width.
# Note:The bivariate analogue of a histogram is known as a "hexbin" plot, because it
# shows the counts of observations that fall within hexagonal bins. This plot works best
# with relatively large datasets. It's available through the matplotlib plt.hexbin function
# and as a style in jointplot(). It looks best with a white background.
# 16. Write a Python program to create a joinplot using "kde" to describe individual
# distributions on the same plot between Sepal length and Sepal width.
# Note:The kernel density estimation (kde) procedure visualize a bivariate distribution.
# In seaborn, this kind of plot is shown with a contour plot and is available as a style in
# jointplot().
# 17. Write a Python program to draw a scatterplot, then add a joint density estimate to
# describe individual distributions on the same plot between Sepal length and Sepal
# width.
# 18. Write a Python program to find the correlation between variables of iris data. Also
# create a hitmap using Seaborn to present their relations.

# 19. Write a Python program to create a box plot (or box-and-whisker plot) which shows
# the distribution of quantitative data in a way that facilitates comparisons between
# variables or across levels of a categorical variable of iris dataset. Use seaborn.
# 20. Write a Python program to split the iris dataset into its attributes (X) and labels (y).
# The X variable contains the first four columns (i.e. attributes) and y contains the labels
# of the dataset.
# 21. Write a Python program using Scikit-learn to split the iris dataset into 70% train data
# and 30% test data. Out of total 150 records, the training set will contain 120 records
# and the test set contains 30 of those records. Print both datasets.
# 22. Write a Python program using Scikit-learn to convert Species columns in a numerical
# column of the iris dataframe. To encode this data map convert each value to a number.
# e.g. Iris-setosa:0, Iris-versicolor:1, and Iris-virginica:2. Now print the iris dataset into
# 80% train data and 20% test data. Out of total 150 records, the training set will contain
# 120 records and the test set contains 30 of those records. Print both datasets.